#!/bin/sh
#
# Deploy Lambda functions to Amazon CloudFront.
#
# Dependencies:
#   aws-sam-cli
#

#
# Check dependencies.
#
if [ ! `which sam` ]; then
  echo "aws-sam-cli is not installed. Exiting."
  exit 1
fi

#
# Support arguments.
#
profile_args="--profile default"

if [ "$1" = "--profile" ] && [ -n $2 ]; then
  profile_args="--profile $2"
fi

#
# Deploy functions.
#
sam build $profile_args && sam deploy $profile_args --resolve-image-repos
