version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HumanFaceApi"
s3_bucket = "aws-sam.functions"
s3_prefix = "cloudFormationStack-HumanFaceApi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
